### ISSUE TITLE
Only check files that were changed

### ISSUE THREAD

**Issue by misode** [ChenCMD/datapack-linter#4]
This would greatly reduce the time it takes to check large repositories. For example the GM4 repo [currently takes 18 minutes](https://github.com/misode/GM4_Clone/runs/1913063365).

It would need to store a cache of which files depend on other files, in order to re-validate those as well.

**Comment by ChenCMD** [comment]
You need to recheck not only the modified file, but also the cache defined in the modified file.
This is probably a bit difficult to implement and may take some time to develop.
